### PR TITLE
Fix list all of versions

### PR DESCRIPTION
**Pull request by rajatvig**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Hi @rajatvig. Thank you for sending this PR. I'll try it out and get back to you.

My earlier attempt at getting the list dynamically would fail intermittently, that is why I removed it
See: https://github.com/mrinalwadhwa/asdf-bazel/issues/1

**Comment by rajatvig** [comment]
Did it work for you?

**Comment by x80486** [comment]
Hello there! Can we merge this one?

**Comment by rajatvig** [comment]
@x80486  `asdf plugin-add bazel https://github.com/rajatvig/asdf-bazel.git` should work in the interim. Have raised a [PR](https://github.com/asdf-vm/asdf-plugins/pull/57) to have mine be the default but that too has not merged.

**Comment by rajatvig** [comment]
This was updated upstream

**Pull request closed without merging**
